services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - generapp-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
  generapp:
    build:
      context: .
      args:
        APP_VERSION: ${APP_VERSION:-1.3.8}
    image: generapp:1.3.2
    container_name: generapp
    restart: unless-stopped
    pull_policy: never
    ports:
      - "30080:3000"
    environment:
      HOSTNAME: "0.0.0.0"
      APP_NAME: "GenerApp"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      COOKIE_SECURE: ${COOKIE_SECURE}
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://172.16.30.2:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  generapp-db:
