import { NextResponse } from "next/server";
import crypto from "node:crypto";
import { current, database } from "../../../../lib/auth";
export const dynamic = "force-dynamic";
async function auth(request) { const user = await current(request); if (!user) return null; await database().query("CREATE TABLE IF NOT EXISTS transaction_payees (id VARCHAR(36) PRIMARY KEY, name VARCHAR(190) NOT NULL, category_id VARCHAR(36) NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES transaction_categories(id) ON DELETE SET NULL)"); return user; }
export async function GET(request) { if (!await auth(request)) return NextResponse.json({ error: "Non autorizzato" }, { status: 401 }); const [payees] = await database().query("SELECT p.id, p.name, p.category_id AS categoryId, p.active, c.name AS categoryName FROM transaction_payees p LEFT JOIN transaction_categories c ON c.id = p.category_id ORDER BY p.name"); return NextResponse.json({ payees }); }
export async function POST(request) { const user = await auth(request); if (!user || user.role !== "admin") return NextResponse.json({ error: "Solo gli amministratori possono gestire i destinatari" }, { status: 403 }); const body = await request.json(); if (!body.name?.trim()) return NextResponse.json({ error: "Inserisci il nome del destinatario" }, { status: 400 }); const id = crypto.randomUUID(); await database().execute("INSERT INTO transaction_payees (id, name, category_id, active) VALUES (?, ?, ?, ?)", [id, body.name.trim(), body.categoryId || null, body.active === false ? 0 : 1]); return NextResponse.json({ id }, { status: 201 }); }
export async function PUT(request) { const user = await auth(request); if (!user || user.role !== "admin") return NextResponse.json({ error: "Non autorizzato" }, { status: 403 }); const body = await request.json(); await database().execute("UPDATE transaction_payees SET name = ?, category_id = ?, active = ? WHERE id = ?", [body.name?.trim(), body.categoryId || null, body.active ? 1 : 0, body.id]); return NextResponse.json({ ok: true }); }
export async function DELETE(request) { const user = await auth(request); if (!user || user.role !== "admin") return NextResponse.json({ error: "Non autorizzato" }, { status: 403 }); await database().execute("DELETE FROM transaction_payees WHERE id = ?", [new URL(request.url).searchParams.get("id")]); return NextResponse.json({ ok: true }); }
