"use client";
import { useEffect, useState } from "react";

const empty = { id: "", username: "", password: "", role: "user", active: true };
export default function UsersPage() {
  const [users, setUsers] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(false); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { const response = await fetch("/api/users"); const data = await response.json(); if (!response.ok) setMessage(data.error || "Non autorizzato"); else setUsers(data.users || []); setLoading(false); }
  useEffect(() => { load(); }, []);
  function edit(user) { setForm({ id: user.id, username: user.username, password: "", role: user.role, active: Boolean(user.active) }); setEditing(true); setMessage(""); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function reset() { setForm(empty); setEditing(false); setMessage(""); }
  async function save(event) { event.preventDefault(); setMessage(""); const method = editing ? "PUT" : "POST"; const body = editing ? form : { username: form.username, password: form.password, role: form.role }; const response = await fetch("/api/users", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || "Operazione non riuscita"); setMessage(editing ? "Utente aggiornato" : "Utente creato"); reset(); load(); }
  async function remove(user) { if (user.role === "admin") return setMessage("Gli amministratori non possono essere eliminati da questa schermata"); if (!window.confirm(`Eliminare l'utente ${user.username}?`)) return; const response = await fetch(`/api/users?id=${user.id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setMessage(data.error || "Eliminazione non riuscita"); load(); }
  if (loading) return <main className="settings-page"><p>Caricamento...</p></main>;
  return <main className="settings-page users-page"><header className="settings-header"><a href="/conti">← Conti</a><p className="eyebrow">Gestione</p><h1>Utenti</h1><p>Crea e amministra gli account che possono accedere al sistema.</p></header><section className="settings-card user-crud-card"><div className="crud-title"><div><h2>{editing ? "Modifica utente" : "Nuovo utente"}</h2><p>{editing ? "Aggiorna ruolo, stato o credenziali." : "Aggiungi un nuovo account al sistema."}</p></div>{editing && <button className="secondary-button" onClick={reset}>Annulla</button>}</div><form className="crud-form" onSubmit={save}><label>Username<input value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} required /></label><label>Password<input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder={editing ? "Lascia vuota per non cambiarla" : "Minimo 8 caratteri"} minLength={editing && !form.password ? undefined : 8} required={!editing} /></label><label>Ruolo<select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><option value="user">Utente</option><option value="admin">Amministratore</option></select></label>{editing && <label className="checkbox-label"><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} /> Account attivo</label>}<button type="submit">{editing ? "Salva modifiche" : "Crea utente"}</button></form>{message && <p className={message.includes("non") || message.includes("errore") ? "error" : "success"}>{message}</p>}</section><section className="settings-card user-table-card"><div className="crud-title"><div><h2>Utenti del sistema</h2><p>{users.length} account registrati</p></div></div><div className="users-table"><div className="user-table-head"><span>Utente</span><span>Ruolo</span><span>Stato</span><span>Azioni</span></div>{users.map(user => <div className="user-table-row" key={user.id}><div className="table-user"><span className="table-avatar">{user.username[0].toUpperCase()}</span><div><strong>{user.username}</strong><small>{user.createdAt ? new Date(user.createdAt).toLocaleDateString("it-IT") : ""}</small></div></div><span className="role-badge">{user.role === "admin" ? "Amministratore" : "Utente"}</span><span className={user.active ? "status-active" : "status-inactive"}>{user.active ? "Attivo" : "Disattivato"}</span><div className="table-actions"><button onClick={() => edit(user)}>Modifica</button>{user.role !== "admin" && <button className="delete-button" onClick={() => remove(user)}>Elimina</button>}</div></div>)}</div></section></main>;
}
