import crypto from "node:crypto";
import mysql from "mysql2/promise";

export const SESSION_TIMEOUT_MS = Number(process.env.SESSION_TIMEOUT_MS || process.env.SESSION_INACTIVITY_MS || 30 * 60 * 1000);

let pool;
function db() { if (!pool) pool = mysql.createPool({ host: process.env.DB_HOST || "mariadb", port: Number(process.env.DB_PORT || 3306), user: process.env.DB_USER || "generapp", password: process.env.DB_PASSWORD || "", database: process.env.DB_NAME || "generapp", waitForConnections: true, connectionLimit: 10 }); return pool; }
async function setup() { const connection = await db().getConnection(); try { await connection.query("CREATE TABLE IF NOT EXISTS users (id VARCHAR(36) PRIMARY KEY, username VARCHAR(190) UNIQUE NOT NULL, password TEXT NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'user', active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)"); await connection.query("CREATE TABLE IF NOT EXISTS sessions (token VARCHAR(64) PRIMARY KEY, user_id VARCHAR(36) NOT NULL, expires_at BIGINT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)"); await connection.query("CREATE TABLE IF NOT EXISTS bank_accounts (id VARCHAR(36) PRIMARY KEY, name VARCHAR(190) NOT NULL, initial_balance DECIMAL(15,2) NOT NULL DEFAULT 0, currency VARCHAR(3) NOT NULL DEFAULT 'EUR', active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)"); await connection.query("CREATE TABLE IF NOT EXISTS bank_imports (id VARCHAR(36) PRIMARY KEY, account_id VARCHAR(36) NOT NULL, file_name VARCHAR(255) NOT NULL, mime_type VARCHAR(150), file_data MEDIUMBLOB NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (account_id) REFERENCES bank_accounts(id) ON DELETE CASCADE)"); await connection.query("CREATE TABLE IF NOT EXISTS bank_transactions (id VARCHAR(36) PRIMARY KEY, account_id VARCHAR(36) NOT NULL, import_id VARCHAR(36) NULL, transaction_date DATE NOT NULL, description VARCHAR(500) NOT NULL, amount DECIMAL(15,2) NOT NULL, category VARCHAR(100) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (account_id) REFERENCES bank_accounts(id) ON DELETE CASCADE, FOREIGN KEY (import_id) REFERENCES bank_imports(id) ON DELETE SET NULL)"); for (const column of ["first_name VARCHAR(100) NULL", "last_name VARCHAR(100) NULL", "avatar MEDIUMTEXT NULL"]) { try { await connection.query(`ALTER TABLE users ADD COLUMN ${column}`); } catch (error) { if (error.code !== "ER_DUP_FIELDNAME") throw error; } } } finally { connection.release(); } }
export async function databaseSetup() { await setup(); }
export function database() { return db(); }
async function settingsSetup() { await db().query("CREATE TABLE IF NOT EXISTS app_settings (setting_key VARCHAR(100) PRIMARY KEY, setting_value MEDIUMTEXT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)"); }
function hash(value) { const salt = crypto.randomBytes(16).toString("hex"); return `${salt}:${crypto.scryptSync(value, salt, 64).toString("hex")}`; }
function valid(value, stored) { const [salt, key] = stored.split(":"); return crypto.timingSafeEqual(Buffer.from(key, "hex"), crypto.scryptSync(value, salt, 64)); }
export async function needsSetup() { await setup(); const [rows] = await db().query("SELECT COUNT(*) AS count FROM users"); return Number(rows[0].count) === 0; }
export async function createFirstAdmin(username, password) { if (!username || !password || password.length < 8 || !(await needsSetup())) throw new Error("INVALID_SETUP"); const user = { id: crypto.randomUUID(), username, role: "admin", active: 1 }; await db().execute("INSERT INTO users (id, username, password, role) VALUES (?, ?, ?, 'admin')", [user.id, username, hash(password)]); return user; }
export async function login(username, password) { await setup(); const [rows] = await db().execute("SELECT * FROM users WHERE username = ? AND active = 1", [username]); const user = rows[0]; if (!user || !valid(password, user.password)) return null; const token = crypto.randomBytes(32).toString("hex"); const expiresAt = Date.now() + SESSION_TIMEOUT_MS; await db().execute("INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)", [token, user.id, expiresAt]); return { token, user: { id: user.id, username: user.username, role: user.role } }; }
export async function current(request) { const token = request.cookies.get("generapp_session")?.value; if (!token) return null; await setup(); const now = Date.now(); const [rows] = await db().execute("SELECT u.id, u.username, u.role FROM sessions s JOIN users u ON u.id = s.user_id WHERE s.token = ? AND s.expires_at > ? AND u.active = 1", [token, now]); if (!rows[0]) return null; await db().execute("UPDATE sessions SET expires_at = ? WHERE token = ?", [now + SESSION_TIMEOUT_MS, token]); return rows[0]; }
export function sessionCookie(token) { return { name: "generapp_session", value: token, httpOnly: true, sameSite: "lax", secure: process.env.COOKIE_SECURE === "true", maxAge: Math.floor(SESSION_TIMEOUT_MS / 1000), path: "/" }; }
export async function logout(request) { const token = request.cookies.get("generapp_session")?.value; if (token) await db().execute("DELETE FROM sessions WHERE token = ?", [token]); }
export async function listUsers() { await setup(); const [rows] = await db().query("SELECT id, username, role, active, created_at AS createdAt FROM users ORDER BY username"); return rows; }
export async function addUser(username, password, role = "user") { if (!username || !password || password.length < 8 || !["user", "admin"].includes(role)) throw new Error("INVALID_DATA"); const user = { id: crypto.randomUUID(), username, role, active: 1 }; try { await db().execute("INSERT INTO users (id, username, password, role) VALUES (?, ?, ?, ?)", [user.id, username, hash(password), role]); return user; } catch (error) { if (error.code === "ER_DUP_ENTRY") throw new Error("USERNAME_EXISTS"); throw error; } }
export async function removeUser(id) { const [result] = await db().execute("DELETE FROM users WHERE id = ? AND role != 'admin'", [id]); return result.affectedRows > 0; }
export async function updateUser(id, { username, password, role, active }) { await setup(); if (!username || !["user", "admin"].includes(role) || ![0, 1, true, false].includes(active)) throw new Error("INVALID_DATA"); try { if (password) await db().execute("UPDATE users SET username = ?, password = ?, role = ?, active = ? WHERE id = ?", [username, hash(password), role, active ? 1 : 0, id]); else await db().execute("UPDATE users SET username = ?, role = ?, active = ? WHERE id = ?", [username, role, active ? 1 : 0, id]); } catch (error) { if (error.code === "ER_DUP_ENTRY") throw new Error("USERNAME_EXISTS"); throw error; } const [rows] = await db().execute("SELECT id, username, role, active, created_at AS createdAt FROM users WHERE id = ?", [id]); return rows[0] || null; }
export async function getProfile(userId) { await setup(); const [rows] = await db().execute("SELECT id, username, first_name AS firstName, last_name AS lastName, avatar, role FROM users WHERE id = ? AND active = 1", [userId]); return rows[0] || null; }
export async function updateProfile(userId, { firstName, lastName, avatar, password }) { await setup(); if (password) { await db().execute("UPDATE users SET first_name = ?, last_name = ?, avatar = ?, password = ? WHERE id = ?", [firstName || null, lastName || null, avatar || null, hash(password), userId]); } else { await db().execute("UPDATE users SET first_name = ?, last_name = ?, avatar = ? WHERE id = ?", [firstName || null, lastName || null, avatar || null, userId]); } return getProfile(userId); }
export async function getAppSettings() { await setup(); await settingsSetup(); const [rows] = await db().query("SELECT setting_key AS settingKey, setting_value AS settingValue FROM app_settings WHERE setting_key IN ('brand_logo', 'brand_name')"); return Object.fromEntries(rows.map(row => [row.settingKey, row.settingValue || ""])); }
export async function saveAppSettings({ logo, name }) { await setup(); await settingsSetup(); await db().execute("INSERT INTO app_settings (setting_key, setting_value) VALUES ('brand_logo', ?), ('brand_name', ?) ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)", [logo || "", name || "GenerApp"]); return getAppSettings(); }
