import { NextResponse } from "next/server";
import crypto from "node:crypto";
import { current, database, databaseSetup } from "../../../../lib/auth";

export const dynamic = "force-dynamic";
async function auth(request) { const user = await current(request); if (!user) return null; await databaseSetup(); return user; }
async function ensureTables() { await database().query("CREATE TABLE IF NOT EXISTS transaction_categories (id VARCHAR(36) PRIMARY KEY, name VARCHAR(150) NOT NULL, parent_id VARCHAR(36) NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)"); await database().query("CREATE TABLE IF NOT EXISTS transaction_payees (id VARCHAR(36) PRIMARY KEY, name VARCHAR(190) NOT NULL, category_id VARCHAR(36) NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)"); await database().query("CREATE TABLE IF NOT EXISTS transaction_rules (id VARCHAR(36) PRIMARY KEY, name VARCHAR(190) NOT NULL, active TINYINT(1) NOT NULL DEFAULT 1, match_field VARCHAR(30) NOT NULL, match_operator VARCHAR(30) NOT NULL, match_value VARCHAR(255) NOT NULL, action_category_id VARCHAR(36) NULL, action_payee_id VARCHAR(36) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)"); }

export async function GET(request) { if (!await auth(request)) return NextResponse.json({ error: "Non autorizzato" }, { status: 401 }); await ensureTables(); const [categories] = await database().query("SELECT id, name, parent_id AS parentId, active FROM transaction_categories ORDER BY name"); const [payees] = await database().query("SELECT id, name, category_id AS categoryId, active FROM transaction_payees ORDER BY name"); const [rules] = await database().query("SELECT r.name, r.active, r.match_field AS matchField, r.match_operator AS matchOperator, r.match_value AS matchValue, c.name AS categoryName, p.name AS payeeName FROM transaction_rules r LEFT JOIN transaction_categories c ON c.id = r.action_category_id LEFT JOIN transaction_payees p ON p.id = r.action_payee_id ORDER BY r.created_at"); return NextResponse.json({ version: 1, exportedAt: new Date().toISOString(), categories, payees, rules }); }

export async function POST(request) { const user = await auth(request); if (!user || user.role !== "admin") return NextResponse.json({ error: "Solo gli amministratori possono importare la configurazione" }, { status: 403 }); await ensureTables(); let backup; try { backup = await request.json(); } catch { return NextResponse.json({ error: "File JSON non valido" }, { status: 400 }); } if (!Array.isArray(backup.categories) || !Array.isArray(backup.payees) || !Array.isArray(backup.rules)) return NextResponse.json({ error: "Backup incompleto" }, { status: 400 }); const categoryIds = new Map(); for (const item of backup.categories) { const id = crypto.randomUUID(); await database().execute("INSERT INTO transaction_categories (id, name, parent_id, active) VALUES (?, ?, NULL, ?) ON DUPLICATE KEY UPDATE active = VALUES(active)", [id, String(item.name).trim(), item.active === false ? 0 : 1]); const [rows] = await database().execute("SELECT id FROM transaction_categories WHERE name = ? LIMIT 1", [String(item.name).trim()]); categoryIds.set(String(item.name).trim(), rows[0]?.id || id); } const payeeIds = new Map(); for (const item of backup.payees) { const id = crypto.randomUUID(); const categoryId = categoryIds.get(item.categoryName) || null; await database().execute("INSERT INTO transaction_payees (id, name, category_id, active) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE category_id = VALUES(category_id), active = VALUES(active)", [id, String(item.name).trim(), categoryId, item.active === false ? 0 : 1]); const [rows] = await database().execute("SELECT id FROM transaction_payees WHERE name = ? LIMIT 1", [String(item.name).trim()]); payeeIds.set(String(item.name).trim(), rows[0]?.id || id); } let importedRules = 0; for (const item of backup.rules) { const categoryId = categoryIds.get(item.categoryName) || null; const payeeId = payeeIds.get(item.payeeName) || null; await database().execute("INSERT INTO transaction_rules (id, name, active, match_field, match_operator, match_value, action_category_id, action_payee_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", [crypto.randomUUID(), String(item.name).trim(), item.active === false ? 0 : 1, item.matchField, item.matchOperator, String(item.matchValue), categoryId, payeeId]); importedRules++; } return NextResponse.json({ imported: { categories: backup.categories.length, payees: backup.payees.length, rules: importedRules } }); }
