import { NextResponse } from "next/server";
import crypto from "node:crypto";
import { current, database } from "../../../../lib/auth";
export const dynamic = "force-dynamic";
async function auth(request) { const user = await current(request); if (!user) return null; await database().query("CREATE TABLE IF NOT EXISTS transaction_categories (id VARCHAR(36) PRIMARY KEY, name VARCHAR(150) NOT NULL, parent_id VARCHAR(36) NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (parent_id) REFERENCES transaction_categories(id) ON DELETE CASCADE)"); return user; }
export async function GET(request) { if (!await auth(request)) return NextResponse.json({ error: "Non autorizzato" }, { status: 401 }); const [categories] = await database().query("SELECT id, name, parent_id AS parentId, active, created_at AS createdAt FROM transaction_categories ORDER BY name"); return NextResponse.json({ categories }); }
export async function POST(request) { const user = await auth(request); if (!user || user.role !== "admin") return NextResponse.json({ error: "Solo gli amministratori possono gestire le categorie" }, { status: 403 }); const body = await request.json(); if (!body.name?.trim()) return NextResponse.json({ error: "Inserisci il nome della categoria" }, { status: 400 }); const id = crypto.randomUUID(); await database().execute("INSERT INTO transaction_categories (id, name, parent_id) VALUES (?, ?, ?)", [id, body.name.trim(), body.parentId || null]); return NextResponse.json({ id }, { status: 201 }); }
export async function PUT(request) { const user = await auth(request); if (!user || user.role !== "admin") return NextResponse.json({ error: "Non autorizzato" }, { status: 403 }); const body = await request.json(); await database().execute("UPDATE transaction_categories SET name = ?, parent_id = ?, active = ? WHERE id = ?", [body.name?.trim(), body.parentId || null, body.active ? 1 : 0, body.id]); return NextResponse.json({ ok: true }); }
export async function DELETE(request) { const user = await auth(request); if (!user || user.role !== "admin") return NextResponse.json({ error: "Non autorizzato" }, { status: 403 }); await database().execute("DELETE FROM transaction_categories WHERE id = ?", [new URL(request.url).searchParams.get("id")]); return NextResponse.json({ ok: true }); }
