"use client";
import { useEffect, useState } from "react";

export default function ProfilePage() {
  const [profile, setProfile] = useState(null); const [form, setForm] = useState({ firstName: "", lastName: "", avatar: "", password: "", confirmPassword: "" }); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/profile", { credentials: 'include' }).then(r => r.json()).then(data => { if (data.profile) { setProfile(data.profile); setForm(current => ({ ...current, firstName: data.profile.firstName || "", lastName: data.profile.lastName || "", avatar: data.profile.avatar || "" })); } else setMessage(data.error || "Errore di caricamento"); }).catch(() => setMessage("Errore di caricamento")); }, []);
  function chooseAvatar(event) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 1_500_000) return setMessage("L’avatar deve essere più piccolo di 1,5 MB"); const reader = new FileReader(); reader.onload = () => setForm(current => ({ ...current, avatar: reader.result })); reader.readAsDataURL(file); }
  async function save(event) { event.preventDefault(); setMessage(""); if (form.password && form.password !== form.confirmPassword) return setMessage("Le password non coincidono"); const response = await fetch("/api/profile", { method: "PUT", credentials: 'include', headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || "Salvataggio non riuscito"); setProfile(data.profile); setForm(current => ({ ...current, password: "", confirmPassword: "" })); setMessage("Profilo aggiornato correttamente"); }
  if (!profile) return <main className="settings-page"><p>{message || "Caricamento..."}</p></main>;
  return <main className="settings-page profile-page"><header className="settings-header"><a href="/">← Dashboard</a><p className="eyebrow">Account</p><h1>Il mio profilo</h1><p>Gestisci i tuoi dati personali, l’avatar e la password.</p></header><form className="settings-card" onSubmit={save}><div className="profile-hero"><div className="profile-avatar">{form.avatar ? <img src={form.avatar} alt="Avatar profilo" /> : (profile.username[0] || "U").toUpperCase()}</div><div><h2>{form.firstName || form.lastName ? `${form.firstName} ${form.lastName}` : profile.username}</h2><p>{profile.role === "admin" ? "Amministratore" : "Utente"} · @{profile.username}</p></div></div><div className="settings-section"><h2>Dati personali</h2><div className="profile-fields"><label>Nome<input value={form.firstName} onChange={e => setForm({ ...form, firstName: e.target.value })} maxLength={100} /></label><label>Cognome<input value={form.lastName} onChange={e => setForm({ ...form, lastName: e.target.value })} maxLength={100} /></label></div><label>Avatar<input type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseAvatar} /><small>JPG, PNG o WebP · massimo 1,5 MB</small></label><h2 className="password-title">Sicurezza</h2><p>Lascia vuoti i campi se non vuoi modificare la password.</p><div className="profile-fields"><label>Nuova password<input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} minLength={8} autoComplete="new-password" /></label><label>Conferma password<input type="password" value={form.confirmPassword} onChange={e => setForm({ ...form, confirmPassword: e.target.value })} minLength={8} autoComplete="new-password" /></label></div></div><div className="settings-actions"><span className={message.includes("correttamente") ? "success" : "error"}>{message}</span><button type="submit">Salva profilo</button></div></form></main>;
}
